const MERMAID_CONFIG = "%%{init: {\"theme\":\"dark\",\"themeVariables\":{\"fontSize\":\"16px\",\"background\":\"#07111e\",\"primaryColor\":\"#12233a\",\"primaryTextColor\":\"#e7edf7\",\"primaryBorderColor\":\"#6fe7c0\",\"lineColor\":\"#6fe7c0\",\"clusterBkg\":\"#0d1a2b\",\"clusterBorder\":\"#2a4160\",\"edgeLabelBackground\":\"#0d1a2b\",\"fontFamily\":\"Hiragino Kaku Gothic ProN, Noto Sans JP, sans-serif\"},\"flowchart\":{\"subGraphTitleMargin\":{\"top\":10,\"bottom\":28}}}}%%\n";
export const DIAGRAMS = {
    0: MERMAID_CONFIG + "%%{init: {'flowchart': {'subGraphTitleMargin': {'top': 10, 'bottom': 28}}} }%%\nflowchart TB\nBook[\"Beautiful Testing<br/>23エッセイ・27人の著者\"] --> P1\nBook --> P2\nBook --> P3\n\nsubgraph P1[\"Part I: Beautiful Testers\"]\ndirection TB\nC1[\"第1章: Was It Good for You?\"] --> C2[\"第2章: ステークホルダーを満たす\"] --> C3[\"第3章: OSSのQAコミュニティ構築\"] --> C4[\"第4章: 協働的パフォーマンステスト\"]\nend\n\nsubgraph P2[\"Part II: Beautiful Process\"]\ndirection TB\nC5[\"第5章: ファジングテスト\"] --> C6[\"第6章: バグ管理\"] --> C7[\"第7章: XMPPテスト\"] --> C8[\"第8章: 大規模テスト自動化\"] --> C9[\"第9章: 継続的インテグレーション\"] --> C10[\"第10章: 乱数生成器のテスト\"] --> C11[\"第11章: 変更中心テスト\"] --> C12[\"第12章: 実利用環境でのテスト\"] --> C13[\"第13章: 創造的プロセスとしての開発\"] --> C14[\"第14章: テスト駆動開発\"] --> C15[\"第15章: ビジネス成功の礎\"] --> C16[\"第16章: Socialtextの事例\"] --> C17[\"第17章: 効率的なテスト\"]\nend\n\nsubgraph P3[\"Part III: Beautiful Tools\"]\ndirection TB\nC18[\"第18章: ミューテーションテスト\"] --> C19[\"第19章: リファレンステスト\"] --> C20[\"第20章: ClamAVのテスト\"] --> C21[\"第21章: Windmillでのテスト\"] --> C22[\"第22章: 100万ページのテスト\"] --> C23[\"第23章: マルチマシン環境テスト\"]\nend",
    1: MERMAID_CONFIG + "flowchart TB\nCommit[\"トリガー: コミット / プルリクエスト\"] --> Static[\"静的解析<br/>Lint / 型チェック\"]\nStatic --> Unit[\"ユニットテスト<br/>Small\"]\nUnit -->|\"プルリクエストのみ\"| Integration[\"統合テスト<br/>Medium\"]\nRelease[\"トリガー: リリース前 / ナイトリー\"] --> E2E[\"E2Eテスト<br/>Large\"]\nManual[\"探索的テスト<br/>手動・CIとは独立して随時実施\"]",
    2: MERMAID_CONFIG + "flowchart LR\nA[\"Red<br/>失敗するテストを書く\"] --> B[\"Green<br/>最小限の実装でパスさせる\"]\nB --> C[\"Refactor<br/>設計を整える\"]\nC --> A",
    3: MERMAID_CONFIG + "flowchart TB\nCharter[\"チャーター作成<br/>調査対象と時間枠を決める\"] --> Session[\"セッション実行<br/>集中的に探索する\"]\nSession --> Debrief[\"デブリーフ<br/>発見を報告・共有する\"]\nDebrief --> Charter",
    4: MERMAID_CONFIG + "flowchart LR\nFound[\"発見<br/>報告\"] --> Triage[\"トリアージ<br/>重要度と優先度の判定\"]\nTriage --> Assigned[\"担当者アサイン\"]\nAssigned --> Fixed[\"修正\"]\nFixed --> Verify[\"検証\"]\nVerify -->|\"再現する\"| Assigned\nVerify -->|\"解決\"| Closed[\"クローズ\"]",
    5: MERMAID_CONFIG + "flowchart TB\nCommit[\"コミット<br/>（毎回実行）\"] --> StaticC2[\"静的解析\"]\nStaticC2 --> SmallC[\"Smallテスト<br/>数秒で完了\"]\nSmallC -->|\"失敗\"| Feedback[\"開発者へ即座にフィードバック\"]\nPR2[\"プルリクエスト\"] --> StaticP2[\"静的解析\"]\nStaticP2 --> SmallP[\"Smallテスト<br/>数秒で完了\"]\nSmallP --> Medium[\"Mediumテスト<br/>数分で完了\"]\nMedium --> Merge[\"マージ可能\"]\nSmallP -->|\"失敗\"| Feedback\nMedium -->|\"失敗\"| Feedback\nFeedback --> Fix2[\"修正して再度push\"]",
    6: MERMAID_CONFIG + "flowchart TB\nNightly[\"ナイトリー（定期実行）\"] --> Large[\"Largeテスト<br/>ネットワーク・外部システム連携あり\"]\nRelease[\"リリース前（リリース候補）\"] --> Large\nLarge -->|\"ナイトリーで成功\"| Staging[\"ステージング環境へデプロイ\"]\nLarge -->|\"リリース前チェックで成功\"| Prod[\"本番環境へデプロイ\"]\nLarge -->|\"失敗\"| Triage[\"担当者へ通知しトリアージ\"]\nTriage --> Fix[\"修正して次サイクルへ\"]",
    7: MERMAID_CONFIG + "%%{init: {'flowchart': {'subGraphTitleMargin': {'top': 10, 'bottom': 28}}} }%%\nflowchart TB\nsubgraph Deterministic[\"決定的レイヤー：Fowlerのピラミッド\"]\ndirection TB\nU[\"ユニットテスト\"] --> I[\"統合テスト\"] --> E[\"E2Eテスト\"]\nend\nsubgraph NonDeterministic[\"非決定的レイヤー：LLM/エージェント特有\"]\ndirection TB\nBehavior[\"振る舞いベースのE2E\"] --> Eval[\"モデル評価 Evals\"]\nend\nDeterministic --> NonDeterministic"
} as const;
