const MERMAID_CONFIG =
    '%%{init: {"theme":"dark","fontFamily":"Segoe UI, Helvetica, Arial, sans-serif","flowchart":{"useMaxWidth":false,"htmlLabels":true,"nodeSpacing":45,"rankSpacing":48},"sequence":{"useMaxWidth":false,"actorFontSize":16,"messageFontSize":16,"noteFontSize":16},"themeVariables":{"fontSize":"16px","darkMode":true,"background":"#07111e","primaryColor":"#152238","primaryTextColor":"#f3f5fa","primaryBorderColor":"#3e5c8f","lineColor":"#7c8db0","textColor":"#e3e8f2","edgeLabelBackground":"#101f36","actorBkg":"#152238","actorBorder":"#3e5c8f","actorTextColor":"#f3f5fa","signalColor":"#9fb0cf","signalTextColor":"#e3e8f2","labelBoxBkgColor":"#152238","labelBoxBorderColor":"#3e5c8f","labelTextColor":"#f3f5fa","loopTextColor":"#e3e8f2","noteBkgColor":"#2a2a12","noteTextColor":"#f0e6c0","noteBorderColor":"#6b6230"}}}%%\n';
export const DIAGRAMS = {
    'diagram-architecture':
        MERMAID_CONFIG +
        'flowchart TD\nU["ユーザー (Streamlit UI)"] -->|"質問と選択中のノード"| QPI["Question Processing Interface"]\nQPI --> LG["LangGraph パイプライン"]\nCP["Configuration Provider"] -.->|"設定を提供"| LG\nSP["Schema Provider"] -.->|"LLMフレンドリーなスキーマ"| LG\nLG -->|"生成したCypher"| DB[("Neo4j Database")]\nDB -->|"クエリ結果またはエラー"| LG\nLG -->|"進捗イベントと結果イベント"| QPI\nQPI -->|"リアルタイム更新"| U\nclassDef ext fill:#2e2a5c,stroke:#c9c3f0,color:#f2f0fc;\nclassDef proc fill:#0f3d3a,stroke:#9fe0d6,color:#e8fbf7;\nclass CP,SP,DB ext\nclass QPI,LG proc',
    'diagram-pipeline':
        MERMAID_CONFIG +
        'flowchart TD\nSTART(["START"]) --> ID["intent_detection<br/>意図検出"]\nID --> SE["schema_extraction<br/>スキーマ抽出"]\nSE --> T2C["text_to_cypher<br/>自然言語からCypherへ変換"]\nT2C --> EX["execute_query<br/>クエリ実行"]\nEX -.->|"エラーかつリトライ3回未満"| T2C\nEX -.->|"成功かつoutput_typeがtable"| ENDT(["END (テーブル表示)"])\nEX -.->|"成功かつoutput_typeがgraphまたはmap"| SUM["summarize<br/>要約生成"]\nSUM --> ENDS(["END (要約つきで表示)"])\nEX -.->|"エラーかつリトライ上限到達"| ENDE(["END (エラー表示)"])\nclassDef proc fill:#2e2a5c,stroke:#c9c3f0,color:#f2f0fc;\nclassDef term fill:#5c2028,stroke:#ffb0bd,color:#fff0f2;\nclassDef good fill:#0f3d3a,stroke:#8fe9d8,color:#e8fbf7;\nclass ID,SE,T2C,EX,SUM proc\nclass ENDE term\nclass ENDT,ENDS good',
    'diagram-sequence':
        MERMAID_CONFIG +
        'sequenceDiagram\nparticipant User as "ユーザー"\nparticipant App as "Streamlit App"\nparticipant QPI as "Question Processing Interface"\nparticipant Graph as "LangGraph パイプライン"\nparticipant DB as "Neo4j"\nUser->>App: 質問を入力\nApp->>QPI: process_question(question, selection)\nQPI->>Graph: stream(initial_state)\nloop 各ノードの実行ごと\nGraph-->>QPI: "update" イベント (進捗)\nend\nGraph->>DB: Cypherクエリを実行\nDB-->>Graph: 結果またはエラー\nGraph-->>QPI: "result" イベント (要約・エラー・可視化データ)\nQPI-->>App: 可視化ペイロード (graph・map・table)\nApp-->>User: リアルタイムに画面表示',
} as const satisfies Record<string, string>;
